### PR TITLE
Update Ruby versions

### PR DESCRIPTION
**Pull request by bobvanderlinden**
Automatically created pull-request to update Ruby and Rubygems versions.

This is the result of running:

```
nix run .#update
```

See the workflow here: https://github.com/bobvanderlinden/nixpkgs-ruby/blob/master/.github/workflows/update.yml

### CODE REVIEW

**Comment by phinze** [comment]
@bobvanderlinden Hello! I've been a happy user of this repo for a while now, so thank you for your work on it! 🙇🏻 

I was going to update a project of mine to the most recent version of Ruby and found that 3.1.6 is missing. It looks like the build might have just timed out here and needs a kick?

**Comment by bobvanderlinden** [comment]
Ah! Thanks for the heads-up. I didn't get a notification about the timeout build. Let's see what a few reruns will do.

**Comment by phinze** [comment]
Hm those build failures look like they might be legit... lots of failures building Ruby 2.1.x versions.

I see a lot of this pattern being repeated. Not sure if this is an actual issue though. Will investigate further if I get more time.

```
config.status: creating -darwin23.0-fake.rb
rm: invalid option -- 'a'
Try 'rm --help' for more information.
config.status: error: could not create -darwin23.0-fake.rb
make: *** [Makefile:235: -darwin23.0-fake.rb] Error 1
```

**Comment by bobvanderlinden** [comment]
Ah, the GitHub runner for osx switched from a MacOS 12 x86 image to a MacOS 14 arm64 image. It makes sense that all versions needed to be rebuild and also that older versions of ruby do not build on arm64.
I'll have to do some digging to see what a good solution is. Maybe disable older versions of ruby for darwin-arm64 for now.

**Comment by bobvanderlinden** [comment]
Ignored 2.1.x works for MacOS arm64 :+1:
@phinze thanks for the heads up!

**Comment by phinze** [comment]
Appreciate you digging in and fixing it! 🙌🏻

**Pull request merged**
