### PR TITLE
Make version attribute a set (alternative)

### LINKED ISSUE #34: version attribute is now string, gem module expected set
I think before the version attribute was a set like the default nixkpgs ruby:

```nix
nix-repl> ruby.version
{ __toString = «lambda @ /nix/store/gcdx2aqn80n5n5i66hpz0cj2q3dmzyqn-nixpkgs/nixpkgs/pkgs/development/interpreters/ruby/ruby-version.nix:54:20»;
gitTag = "v2_7_6"; libDir = "2.7.0"; majMin = "2.7"; majMinTiny = "2.7.6";
major = "2"; minor = "7"; patchLevel = null; tail = ""; tiny = "6"; }
```

but this now is just a string:

```nix
nix-repl> outputs.packages.aarch64-darwin."ruby-3.1.3".version                                                                                         "3.1.3"
```

which makes some things in the gem module upset:

```
error: value is a string while a set was expected

       at /nix/store/5hqyy6278jaa3w1d12bhfyx93xw4kyiz-source/pkgs/development/ruby-modules/gem/default.nix:139:79:

          138|   # Introduced in https://github.com/ruby/ruby/commit/0958e19ffb047781fe1506760c7cbd8d7fe74e57
          139|   NIX_CFLAGS_COMPILE = lib.optionals (stdenv.cc.isClang && lib.versionAtLeast ruby.version.major "3") [
             |                                                                               ^
          140|     "-fdeclspec"
(use '--show-trace' to show detailed location information)
```

### PR DESCRIPTION
**Pull request by bobvanderlinden**
Alternative to #35
Closes #34
Closes #35

Makes sure the rubyPackage.version is a set instead of a string to be more compatible with the ruby package in nixpkgs.

Also uses overrides.nix to override the libDir for 1.9.1. This is differently implemented than what nixpkgs does, but using overrides.nix keeps all version-specific changes in one place.

### CODE REVIEW

**Comment by will** [comment]
Thanks for looking into this. This branch though I think still presents version as a string unfortunately:

```
$ direnv reload
error: value is a string while a set was expected

       at /nix/store/5hqyy6278jaa3w1d12bhfyx93xw4kyiz-source/pkgs/development/ruby-modules/gem/default.nix:139:79:

          138|   # Introduced in https://github.com/ruby/ruby/commit/0958e19ffb047781fe1506760c7cbd8d7fe74e57
          139|   NIX_CFLAGS_COMPILE = lib.optionals (stdenv.cc.isClang && lib.versionAtLeast ruby.version.major "3") [
             |                                                                               ^
          140|     "-fdeclspec"
(use '--show-trace' to show detailed location information)
```


```diff
diff --git a/flake.lock b/flake.lock
index c338bc07..76bf9a8c 100644
--- a/flake.lock
+++ b/flake.lock
@@ -37,16 +37,15 @@
         ]
       },
       "locked": {
-        "lastModified": 1672309551,
-        "narHash": "sha256-WZXHlCSreEvGmHGaxo7W8x8uEoXGR6Iy2MBxGl4BOyc=",
-        "owner": "will",
+        "lastModified": 1673366068,
+        "narHash": "sha256-kh245EGEKGME48+MWRGC+OWuJuHJzLjKmUEPQx0HiAo=",
+        "owner": "bobvanderlinden",
         "repo": "nixpkgs-ruby",
-        "rev": "cafe576d67cafb20b06adf1d3ed7f8b60e869a87",
+        "rev": "a22ca32f06a6f952ea405bc571a7f766a2f055c3",
         "type": "github"
       },
       "original": {
-        "owner": "will",
-        "ref": "changeversion",
+        "owner": "bobvanderlinden",
         "repo": "nixpkgs-ruby",
         "type": "github"
       }
diff --git a/flake.nix b/flake.nix
index 0786ea5b..46d0f325 100644
--- a/flake.nix
+++ b/flake.nix
@@ -10,7 +10,8 @@
     #
     # Example: nixpkgs.url = "path:/home/myuser/path/to/nixpkgs";
     nixpkgs.url = "nixpkgs";
-    nixpkgs-ruby.url = "github:will/nixpkgs-ruby?ref=changeversion";
+    # nixpkgs-ruby.url = "github:will/nixpkgs-ruby?ref=changeversion";
+    nixpkgs-ruby.url = "github:bobvanderlinden/nixpkgs-ruby?pr-changeversion";
     nixpkgs-ruby.inputs.nixpkgs.follows = "nixpkgs";
   };
 
```


This flake I think reproduces it:

```nix
{
  description = "ruby test flake";

  inputs = {
    nixpkgs.url = "nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
    # nixpkgs-ruby.url = "github:will/nixpkgs-ruby?ref=changeversion";
    nixpkgs-ruby.url = "github:bobvanderlinden/nixpkgs-ruby?pr-changeversion";
    nixpkgs-ruby.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, flake-utils, nixpkgs-ruby }:
    let
      rubyVersion = "3.1.3";
    in
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        ruby = nixpkgs-ruby.packages.${system}."ruby-${rubyVersion}";

        rubyEnv = pkgs.bundlerEnv {
          name = "ruby-env";
          gemdir = ./.;
          inherit ruby;
        };
      in
      {
        devShell = pkgs.mkShell {
          packages = [ ];

          buildInputs = [
            rubyEnv
            rubyEnv.wrappedRuby
          ];

        };
      }
    );
}
```

with gemeset.nix just being `{}`

**Comment by bobvanderlinden** [comment]
The problem was that `version` was not yet in `passthru`, so it wasn't possible to use `rubyPackage.version`. Thanks for your example. It is working with the latest version.

**Comment by will** [comment]
The last patch `5524b1340fcfe4a547e4a65c63520fc21b0dfbc0` works great!

**Comment by domenkozar** [comment]
For [devenv](https://github.com/domenkozar/devenv-ruby/blob/main/devenv.nix) users this fixes `error: Function called without required argument "rubygems-2_6" at «github:bobvanderlinden/nixpkgs-ruby/b307292b921d60ad14f4586dbc410bc014fd9849»/ruby/overrides.nix:4`

**Pull request merged**
