### PR TITLE
Add possibility to add railsexpress patches

### PR DESCRIPTION
**Pull request by nevesenin**
Hi, I need some more time to test this properly, but I wanted you to know about this to maybe save you some time in case this is on your TODO list. That's why it's WIP.

### CODE REVIEW

**Comment by nevesenin** [comment]
Some additional thoughts on this:
- Ruby 2.7.6 is the first version for which it is possible to add the patches. That's only due to my own personal opinion to not actively support EOL rubies (if I don't need that for myself), since it adds a lot of complexity to a project over time.
- The way this project is structured, the railsexpress part could be moved to a dedicated namespace/directory and equipped with an updater. I'd like to hear your opinion on that.

**Comment by bobvanderlinden** [comment]
Very good to see this change :+1: `useRailsExpress` was unfortunately still left defunct in the code.

I have been thinking what is a good way to resolve these patches from RVM. The problem with having RVM as a whole as a dependency for each Ruby version is that whenever the RVM repository is updated, _all_ Ruby versions that depend on RVM patches need to be rebuild. This is quite intensive as GitHub Actions usually times out a few times when this happens.

Another approach would be to apply individual patch files to individual Ruby versions. So, it would look like:

```
patches = [
    (fetchpatch {
      url = "https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patches/ruby/3.2.2/railsexpress/01-improve-gc-stats.patch";
      hash = "sha256-XXX=";
    })
    (fetchpatch {
      url = "https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patches/ruby/3.2.2/railsexpress/02-malloc-trim-patch.patch";
      hash = "sha256-XXX=";
    })
  ];
```

The patches would be fetched from the patchsets (https://github.com/rvm/rvm/blob/master/patchsets/ruby/3.2.2/railsexpress). It can be done by having update fetch the patches and calculate the hashes and add them to a json file like:

```
{
  "3.2.2": [
    { "url": "https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patches/ruby/3.2.2/railsexpress/01-improve-gc-stats.patch", "hash": "..." },
  ]
}
```

This should then be converted to the `fetchpatch` calls as shown above.
This way, if there is a new patch for one version of Ruby, it won't affect all the others.

In the above example I haven't incorporated multiple patchsets. It might be nice to have this as well, but focus on railsexpress does sound like a good idea.

**Comment by nevesenin** [comment]
Ah, I see. Didn't think about that. Will take care of it as soon as find some time.
Could you please elaborate on what you mean by multiple patchsets? I never stumbled upon any other ruby patch collections. Would love to hear more about it.
My first thought on that is naming conventions in terms of not having a `railsexpress` module and a `railsexpress.json` but a `patchsets` and `patchsets.json` that includes railsexpress patchset handling.

**Comment by bobvanderlinden** [comment]
Patchsets might have not been the best wording, but I see that rvm has more patches than just railsexpress. For instance, there are patches for openssl compatibility. They could be considered a 'default' patcheset.

**Comment by nevesenin** [comment]
The provided `railsexpress.nix` currently applies all patches defined for a specific ruby version. It reads the patchset file (e.g. https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patchsets/ruby/3.2.2/railsexpress) and applies the listed patches, which are downloaded from here https://github.com/skaes/rvm-patchsets/tree/master/patches/ruby/3.2.2/railsexpress. The result (in terms of patches applied) is the same as installing ruby `rvm install 3.2.2 --patch railsexpress`.
I'd like to suggest to go for `useRailsExpress` reflecting this, plus your proposal like
```json
{
  "3.2.2": [
    { "url": "https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patches/ruby/3.2.2/railsexpress/01-improve-gc-stats.patch", "hash": "..." }
    { "url": "https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patches/ruby/3.2.2/railsexpress/02-malloc-trim-patch.patch", "hash": "..." }
    { "url": "https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patches/ruby/3.2.2/railsexpress/03-fix-bigdecimal-linker-problems-on-macos.patch", "hash": "..." }
  ]
}
```
where the urls and hashes are generated from the list of patches in the patchset file mentioned above.

**Comment by emptyflask** [comment]
Since this PR is still open I wanted to point out that the patches are no longer relevant:
https://github.com/skaes/rvm-patchsets/issues/47

**Comment by nevesenin** [comment]
> Since this PR is still open I wanted to point out that the patches are no longer relevant (for most people): [skaes/rvm-patchsets#47](https://github.com/skaes/rvm-patchsets/issues/47)

Yes, I know. At the time of creating the PR I needed/wanted the patches because of the metrics. This changed so I'm not that motivated to work on this PR. And as you already mentioned, most probably no one will use it. Closing it.

**Pull request closed without merging**
